################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

---

name: Check the 'toolset/file/read' Action

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:

  checks:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        type: [file, url, mix]
        include:
          - type: file
            text-file: './toolset/.tests/file/read/test.txt'
            json-file: './toolset/.tests/file/read/test.json'
            text-url: ''
            json-url: ''
          - type: url
            text-file: ''
            json-file: ''
            text-url: 'https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_SHA}/toolset/.tests/file/read/test.txt'
            json-url: 'https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_SHA}/toolset/.tests/file/read/test.json'
          - type: mix
            text-file: './toolset/.tests/file/read/test.txt'
            json-file: './toolset/.tests/file/read/test.json'
            text-url: 'https://httpbin.org/status/400'
            json-url: 'https://httpbin.org/status/404'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Run 'toolset/file/read' action [.txt]
        id: read-text-file
        uses: ./toolset/file/read
        with:
          file: ${{ matrix.text-file }}
          url: ${{ matrix.text-url }}

      - name: Run 'toolset/file/read' action [.json]
        id: read-json-file
        uses: ./toolset/file/read
        with:
          file: ${{ matrix.json-file }}
          url: ${{ matrix.json-url }}

      - name: Check 'toolset/file/read' action
        shell: bash
        run: |
          actual_txt_content="${{ steps.read-text-file.outputs.content }}"
          expected_txt_content="This is a test file.
          This is a new line.
          These are several numbers: 0, 1, 2, 3."

          if [ "$actual_txt_content" != "$expected_txt_content" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The file 'test.txt' is read incorrectly."
            echo "Differences:"
            diff <(echo "$actual_txt_content") <(echo "$expected_txt_content")
            exit 1
          fi

          actual_itemA0="${{ fromJSON(steps.read-json-file.outputs.content).item-A-0 }}"
          expected_itemA0="value-A-0"
          if [ "$actual_itemA0" != "$expected_itemA0" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'item-A-0' item is incorrect."
            echo "Differences:"
            diff <(echo "$actual_itemA0") <(echo "$expected_itemA0")
            exit 1
          fi

          actual_itemA2="${{ fromJSON(steps.read-json-file.outputs.content).item-A-2 }}"
          expected_itemA2=2
          if [ "$actual_itemA0" != "$expected_itemA0" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'item-A-2' item is incorrect."
            exit 1
          fi

          actual_sectionB_itemB0="${{ fromJSON(steps.read-json-file.outputs.content).section-B.item-B-0 }}"
          expected_sectionB_itemB0="value-B-0"
          if [ "$actual_sectionB_itemB0" != "$expected_sectionB_itemB0" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'section-B.item-B-0' item is incorrect."
            echo "Differences:"
            diff <(echo "$actual_sectionB_itemB0") <(echo "$expected_sectionB_itemB0")
            exit 1
          fi

          actual_sectionB_itemB2="${{ fromJSON(steps.read-json-file.outputs.content).section-B.item-B-2 }}"
          expected_sectionB_itemB2=12
          if [ "$actual_sectionB_itemB2" != "$expected_sectionB_itemB2" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'section-B.item-B-2' item is incorrect."
            exit 1
          fi

          actual_arrayC_itemC0="${{ fromJSON(steps.read-json-file.outputs.content).array-C[0].item-C-0 }}"
          expected_arrayC_itemC0="value-C-00"
          if [ "$actual_arrayC_itemC0" != "$expected_arrayC_itemC0" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'array-C[0].item-C-0' item is incorrect."
            echo "Differences:"
            diff <(echo "$actual_arrayC_itemC0") <(echo "$expected_arrayC_itemC0")
            exit 1
          fi

          actual_arrayC_itemC2="${{ fromJSON(steps.read-json-file.outputs.content).array-C[1].item-C-2 }}"
          expected_arrayC_itemC2=212
          if [ "$actual_arrayC_itemC2" != "$expected_arrayC_itemC2" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'array-C[1].item-C-2' item is incorrect."
            exit 1
          fi

          actual_arrayD="${{ fromJSON(steps.read-json-file.outputs.content).array-D[0] }}"
          expected_arrayD="value-D-0"
          if [ "$actual_arrayD" != "$expected_arrayD" ]; then
            echo "::error::The 'toolset/file/read' action failed the tests. The 'array-D[0]' item is incorrect."
            echo "Differences:"
            diff <(echo "$actual_arrayD") <(echo "$expected_arrayD")
            exit 1
          fi
